### ISSUE TITLE
Tag for release 4.0.9

### ISSUE THREAD

**Issue by drewrisinger** [beltoforion/muparserx#102]
It looks like you released a v4.0.9 on 2020-06-19, but there is no corresponding tag. Can you create and push one?
This makes packaging this for downstream systems easier.

**Comment by beltoforion** [comment]
I did not release 4.0.9. The version is marked as a development snapshot.  Version 4.0.8 is still the current release because nothing of substance was added. Essentially I only added new unit tests for bugs that do not exist in muparserx.

I'm aware that publishing a new release will trigger a process downstream. For this reason i will only push the button when I think it is justified. At the moment i do not see the need.

**Comment by drewrisinger** [comment]
Understood. Just got confused by the 4.0.9 language on the master
branch/main readme. Thanks for the clarification.
