### ISSUE TITLE
Large(ish) integers not supported

### ISSUE THREAD

**Issue by GoogleCodeExporter** [beltoforion/muparserx#36]
```
What steps will reproduce the problem?
1. The following code throws:
mup::ParserX parser(mup::pckALL_NON_COMPLEX);
mup::Value value1{0};
mup::Variable variable1{&value1};
parser.DefineVar("v1", variable1);
parser.SetExpr("2147483648");
try {
	cout << parser.Eval().GetInteger() << endl;
} ...

What is the expected output? What do you see instead?

The value is only 2^31, shouldn't values up to 2^64-1 be supported for unsigned 
(long long) integers? Is it possible to specify the type of the variable at 
compile-time (and get a parsing error if it is not used as such in the 
expression)?

Currently I'm planning to use std::enable_if<std::is_integral<... and 
enable_if<is_floating_point<... to use either parser.Eval().GetInteger() or 
parser.Eval().GetFloatingpoint() to return the correct value from the parser. 
It would be nice if all types if integers and floating points were supported...


What version of the product are you using? On what operating system?

3.0.1
```

Original issue reported on code.google.com by `ilja.j.h...@nasa.gov` on 14 Jul 2014 at 2:49

**Comment by jeffreyscottgraham** [comment]
Is there a plan to address this issue?

**Comment by beltoforion** [comment]
When working with large integer number you will receive an overflow exception as soon as the number of digits in the number exceed 15. So internally you'll have 48 bits to work with your integers. Giving you more is a problem. I can only raise proper errors if that happens.

Externally calling GetInteger will only return a 32 bit integer. Thats inconsistent. Maybe i'll remove GetInteger() altogether. I havn't decided yet

**Comment by nasailja** [comment]
If the internal type is always or will always be double or complex double then I vote for removing getinteger(). In safe cases I guess double will be converted to int when needed and otherwise the compiler will warn or give an error in which case the value can be converted explicitly without getinteger().

**Comment by jeffreyscottgraham** [comment]
I have a commercial product that uses the 3x version, and cannot move to the latest version because integer support was removed. Please put it back.

**Comment by beltoforion** [comment]
I don't understand that. the change affected the API only. "Integer support" was always only a label rather then somthing that was done internally. It was a mistake to have it in the first place and a major source of confusion. I just removed value construction from integer. 4.x will work in your code if you cast your integers to a float when creating a variable. Every expression that was computed in 3.x should also compute in 4.x. (Notable exception: Casting to integer)

As far as returning results with GetInteger is concerned i'm currently thinking that this might be usefull in case you have expressions that are supposed to be dealing with integer values exclusively since it will just check the return value for integer properties and return it as such or throw an exception otherwise.

**Comment by guruofquality** [comment]
So I had a small amount of code that broke because of the API change, though it wasnt hard to work around. To me, the integer constructor added a sense of completeness and a way to express the intention "this variable in an integer".

Although I understand that the underlying implementation throws out that intention and just stores a double. So I can see where the confusion comes in. You are damned if you do, damned if you don't... :-P

It might be nice for users of the API to be able to express that intention, and perhaps one day, muparserx internals may may use of that extra piece of information that this variable is an integer (like you said).

**Comment by jeffreyscottgraham** [comment]
In version 3, my code did not need to care if the numerics were floating point, integer,boolean or string, and met requirements perfectly.
In version 4, I need to know if an expression is a pure integer expression or mixed with floating point values too, and worry about precision as well. IMNSHO, that is a major function and responsibility of the library itself.

**Comment by beltoforion** [comment]
Check out 4.0.5 if this is sovling your problem.

**Comment by jeffreyscottgraham** [comment]
Thanks. Will try it out tomorrow!
