### ISSUE TITLE
DLL/Library of muparserx

### ISSUE THREAD

**Issue by ThirtySomething** [beltoforion/muparserx#81]
We've tested both, muparser and also muparserx. We prefer muparserx because of its C++ approach. But unfortunately the MSVC project does not support a DLL/LIB. Is there such a configuration on the roadmap?

**Comment by beltoforion** [comment]
There are no plans to do that and it would not be a good idea since muparserx is using the STL in its public API. Different STL versions are not compatible in their binary interface so muparserx would only ever work with the specifc version of the STL it was compiled against. Even bugfixes to that STL version might break the binary interface and thus muparserx.

**Comment by ThirtySomething** [comment]
Understand. Yes, templated code in a DLL/library can cause heavy problems. You're right.
